# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 04:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quality',
            name='about',
        ),
        migrations.AddField(
            model_name='quality',
            name='brand_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='water.Brand'),
        ),
    ]
